name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: |
          uv run ruff check --output-format=github

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          uv run pytest
