name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}
          retention-days: 1

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}

      - name: Lint code
        run: |
          cd ${{ github.workspace }}
          uv run ruff check --output-format=github

  test:
    needs: [setup, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}

      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          uv run pytest
