name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync

      - name: Cache environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            __pycache__
            ~/.local/bin/uv
            ~/.local/lib/python3.*/site-packages/uv
          key: ${{ runner.os }}-python-${{ hashFiles('**/uv.lock') }}

  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            __pycache__
            ~/.local/bin/uv
            ~/.local/lib/python3.*/site-packages/uv
          key: ${{ runner.os }}-python-${{ hashFiles('**/uv.lock') }}

      - name: Lint code
        run: |
          ~/.local/bin/uv run ruff check --output-format=github

  test:
    needs: [setup, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            __pycache__
            ~/.local/bin/uv
            ~/.local/lib/python3.*/site-packages/uv
          key: ${{ runner.os }}-python-${{ hashFiles('**/uv.lock') }}

      - name: Run tests
        run: |
          ~/.local/bin/uv run pytest
